# Generated by Django 5.0.1 on 2024-01-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.TimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
